# Generated by Django 5.1.2 on 2026-05-30 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_solicitud', '📋 Nueva Solicitud'), ('cotizacion_recibida', '💰 Cotización Recibida'), ('cotizacion_aceptada', '✅ Cotización Aceptada'), ('cotizacion_rechazada', '❌ Cotización Rechazada'), ('solicitud_asignada', '👤 Solicitud Asignada'), ('cambio_estado', '🔄 Cambio de Estado'), ('entrega_recibida', '📁 Entrega Recibida'), ('mensaje_chat', '💬 Nuevo Mensaje'), ('sistema', 'ℹ️ Sistema')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('url_accion', models.CharField(blank=True, help_text='URL a la que redirige al hacer click', max_length=500, verbose_name='URL de acción')),
                ('solicitud_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
