# Generated by Django 5.1.2 on 2026-08-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nueva_solicitud', 'Nueva Solicitud'), ('cotizacion_recibida', 'Cotización Recibida'), ('cotizacion_aceptada', 'Cotización Aceptada'), ('cotizacion_rechazada', 'Cotización Rechazada'), ('solicitud_asignada', 'Solicitud Asignada'), ('cambio_estado', 'Cambio de Estado'), ('entrega_recibida', 'Entrega Recibida'), ('mensaje_chat', 'Nuevo Mensaje'), ('sistema', 'Sistema')], max_length=30, verbose_name='Tipo'),
        ),
    ]
