# Generated by Django 5.1.2 on 2026-05-30 08:28

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('instruccion', 'Instrucción / Enunciado'), ('referencia', 'Material de Referencia'), ('entrega', 'Entrega del Tutor'), ('revision', 'Revisión / Corrección'), ('comprobante', 'Comprobante de Pago'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to=documentos.models.documento_upload_path, verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tamaño_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitudes.solicitudacademica', verbose_name='Solicitud')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
