# Generated by Django 5.1.2 on 2026-08-04 04:14

import django.core.files.storage
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url=None,
                    location=settings.PRIVATE_MEDIA_ROOT,
                ),
                upload_to=documentos.models.documento_upload_path,
                verbose_name='Archivo',
            ),
        ),
    ]
