# Generated by Django 5.1.2 on 2026-08-26 04:26

import django.core.files.storage
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_subido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\LENOVO\\Desktop\\tareaenminutos_web\\tareaenminutos_web\\media_privada'), upload_to=documentos.models.documento_upload_path, verbose_name='Archivo'),
        ),
    ]
