# Generated by Django 5.1.2 on 2026-05-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='📚', help_text='Emoji o clase de icono', max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área de Conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Descripción / Bio')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación Promedio')),
                ('trabajos_completados', models.PositiveIntegerField(default=0, verbose_name='Trabajos Completados')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para nuevas solicitudes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(blank=True, to='accounts.areaconocimiento', verbose_name='Áreas de Especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
