# Generated by Django 5.1.2 on 2026-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='icono',
            field=models.CharField(default='fa-book-open', help_text='Clase FontAwesome del icono', max_length=50),
        ),
    ]
