# Generated by Django 5.1.2 on 2026-08-04 05:27

from django.db import migrations


def quitar_tutor_a_admins(apps, schema_editor):
    """Rol único: un usuario admin no debe pertenecer al grupo Tutor."""
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    grupo_tutor = Group.objects.filter(name='Tutor').first()
    grupo_admin = Group.objects.filter(name='Administrador').first()
    if grupo_tutor is None:
        return
    admins = User.objects.filter(is_superuser=True)
    if grupo_admin is not None:
        admins = admins | User.objects.filter(groups=grupo_admin)
    admins = admins.distinct()
    for admin in admins:
        admin.groups.remove(grupo_tutor)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_areaconocimiento_icono'),
    ]

    operations = [
        migrations.RunPython(quitar_tutor_a_admins, migrations.RunPython.noop),
    ]
