# Generated by Django 5.1.2 on 2026-08-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rol_unico_quitar_tutor_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Calificación Promedio'),
        ),
    ]
