# Generated by Django 5.1.2 on 2026-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_perfilusuario_calificacion_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última conexión'),
        ),
    ]
