# Generated by Django 5.1.2 on 2026-09-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_perfilusuario_ultima_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_email_chat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
