# Generated by Django 5.1.2 on 2026-08-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('titulo', 'Título'), ('subtitulo', 'Subtítulo'), ('imagen', 'Imagen'), ('cita', 'Cita')], default='texto', max_length=15, verbose_name='Tipo de bloque')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/bloques/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='main_app.blogpost', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Bloque de contenido',
                'verbose_name_plural': 'Bloques de contenido',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
