# Generated by Django 5.1.2 on 2026-08-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_blogblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogblock',
            options={'ordering': ['id'], 'verbose_name': 'Bloque de contenido', 'verbose_name_plural': 'Bloques de contenido'},
        ),
    ]
