# Generated by Django 5.1.2 on 2026-05-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('nueva', 'Nueva'), ('en_cotizacion', 'En Cotización'), ('cotizada', 'Cotizada'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('en_revision', 'En Revisión'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en_disputa', 'En Disputa')], max_length=30, unique=True)),
                ('etiqueta', models.CharField(max_length=50)),
                ('color_hex', models.CharField(default='#6366f1', help_text='Color HEX ej: #6366f1', max_length=7)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de Solicitud',
                'verbose_name_plural': 'Estados de Solicitud',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente')),
                ('cliente_universidad', models.CharField(blank=True, max_length=150, verbose_name='Universidad')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del Trabajo')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('nivel_academico', models.CharField(choices=[('pregrado', 'Pregrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('tecnico', 'Técnico / Tecnólogo')], max_length=20, verbose_name='Nivel Académico')),
                ('tipo_entrega', models.CharField(choices=[('tarea', 'Tarea'), ('taller', 'Taller'), ('examen', 'Examen / Parcial'), ('proyecto', 'Proyecto'), ('ensayo', 'Ensayo'), ('tesis', 'Tesis / Trabajo de Grado'), ('informe', 'Informe / Reporte'), ('presentacion', 'Presentación'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Entrega')),
                ('materia', models.CharField(blank=True, max_length=150, verbose_name='Materia/Asignatura')),
                ('fecha_entrega_cliente', models.DateTimeField(verbose_name='Fecha Límite del Cliente')),
                ('presupuesto_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto del Cliente (COP)')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Final Acordado (COP)')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas (solo Admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.areaconocimiento', verbose_name='Área de Conocimiento')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.estadosolicitud', verbose_name='Estado Actual')),
                ('tutor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Asignado')),
            ],
            options={
                'verbose_name': 'Solicitud Académica',
                'verbose_name_plural': 'Solicitudes Académicas',
                'ordering': ['-created_at'],
                'permissions': [('asignar_tutor', 'Puede asignar tutor a solicitud'), ('ver_notas_internas', 'Puede ver notas internas'), ('cambiar_estado', 'Puede cambiar estado de solicitud')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transiciones_desde', to='solicitudes.estadosolicitud')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transiciones_hacia', to='solicitudes.estadosolicitud')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='solicitudes.solicitudacademica')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-created_at'],
            },
        ),
    ]
