# Generated by Django 5.1.2 on 2026-06-04 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudacademica',
            name='area_conocimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.areaconocimiento', verbose_name='Área de Conocimiento'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='cliente_universidad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Universidad'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='fecha_entrega_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite del Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('pregrado', 'Pregrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('tecnico', 'Técnico / Tecnólogo')], max_length=20, null=True, verbose_name='Nivel Académico'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('tarea', 'Tarea'), ('taller', 'Taller'), ('examen', 'Examen / Parcial'), ('proyecto', 'Proyecto'), ('ensayo', 'Ensayo'), ('tesis', 'Tesis / Trabajo de Grado'), ('informe', 'Informe / Reporte'), ('presentacion', 'Presentación'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Entrega'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='titulo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título del Trabajo'),
        ),
    ]
