# Generated by Django 5.1.2 on 2026-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitudacademica_area_conocimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudacademica',
            name='calificacion_tutor',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Evaluación del administrador sobre el desempeño del tutor', null=True, verbose_name='Puntuación del tutor (0-100)'),
        ),
        migrations.AddField(
            model_name='solicitudacademica',
            name='fecha_calificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de calificación'),
        ),
        migrations.AddField(
            model_name='solicitudacademica',
            name='nota_obtenida',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calificación que el estudiante obtuvo en el trabajo', null=True, verbose_name='Nota obtenida (0-100)'),
        ),
    ]
