# Generated by Django 5.1.2 on 2026-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudacademica_calificacion_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudacademica',
            name='nivel_academico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel Académico'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='prioridad',
            field=models.CharField(default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Entrega'),
        ),
    ]
