# Generated by Django 5.1.2 on 2026-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_solicitudacademica_nivel_academico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudacademica',
            name='fecha_entrega_cliente',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite del Cliente'),
        ),
    ]
