# Generated by Django 5.1.2 on 2026-08-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_normalizar_fecha_entrega_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosolicitud',
            name='nombre',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_cotizacion', 'En Cotización'), ('cotizada', 'Cotizada'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('en_revision', 'En Revisión'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en_disputa', 'En Disputa'), ('en_correccion', 'En Corrección')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='calificacion_tutor',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Se calcula automáticamente a partir de la nota obtenida (nota × 20)', null=True, verbose_name='Puntuación del tutor (0-100)'),
        ),
        migrations.AlterField(
            model_name='solicitudacademica',
            name='nota_obtenida',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calificación que el estudiante obtuvo en el trabajo, escala universitaria 0.0 a 5.0', max_digits=3, null=True, verbose_name='Nota obtenida (0.0-5.0)'),
        ),
    ]
