# Generated by Django 5.1.2 on 2026-08-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_historialestado_cambiado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudacademica',
            name='prioridad',
        ),
    ]
