# Generated by Django 5.1.2 on 2026-08-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_remove_solicitudacademica_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudacademica',
            name='fecha_limite_correccion',
            field=models.DateField(blank=True, help_text='Se fija automáticamente al devolver la tarea al tutor (reactivación).', null=True, verbose_name='Fecha Límite de Corrección'),
        ),
    ]
