# Generated by Django 5.1.2 on 2026-09-01 06:04

from django.db import migrations, models


def actualizar_etiqueta_cotizacion(apps, schema_editor):
    EstadoSolicitud = apps.get_model('solicitudes', 'EstadoSolicitud')
    EstadoSolicitud.objects.filter(nombre='en_cotizacion').update(etiqueta='Cotización')


def revertir_etiqueta_cotizacion(apps, schema_editor):
    EstadoSolicitud = apps.get_model('solicitudes', 'EstadoSolicitud')
    EstadoSolicitud.objects.filter(nombre='en_cotizacion').update(etiqueta='En Cotización')


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_solicitudacademica_fecha_limite_correccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosolicitud',
            name='nombre',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_cotizacion', 'Cotización'), ('cotizada', 'Cotizada'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('en_revision', 'En Revisión'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en_disputa', 'En Disputa'), ('en_correccion', 'En Corrección')], max_length=30, unique=True),
        ),
        migrations.RunPython(actualizar_etiqueta_cotizacion, revertir_etiqueta_cotizacion),
    ]
