# Generated by Django 5.1.2 on 2026-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_alter_estadosolicitud_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosolicitud',
            name='nombre',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_cotizacion', 'Cotización'), ('cotizada', 'Cotizada'), ('en_negociacion', 'En Negociación'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('en_revision', 'En Revisión'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en_disputa', 'En Disputa'), ('en_correccion', 'En Corrección')], max_length=30, unique=True),
        ),
    ]
