# Generated by Django 5.1.2 on 2026-05-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto propuesto (COP)')),
                ('tiempo_estimado_dias', models.PositiveSmallIntegerField(verbose_name='Tiempo estimado (días)')),
                ('fecha_entrega_propuesta', models.DateTimeField(verbose_name='Fecha de entrega propuesta')),
                ('descripcion_propuesta', models.TextField(help_text='Explica cómo abordarás el trabajo y tu experiencia en el área', verbose_name='Descripción de la propuesta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='solicitudes.solicitudacademica', verbose_name='Solicitud')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
                'unique_together': {('solicitud', 'tutor')},
            },
        ),
    ]
