# Generated by Django 5.1.2 on 2026-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_entrega_propuesta',
            field=models.DateField(verbose_name='Fecha de entrega propuesta'),
        ),
    ]
