# Generated by Django 5.1.2 on 2026-08-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_normalizar_fecha_entrega_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion_propuesta',
            field=models.TextField(blank=True, help_text='Explica cómo abordarás el trabajo y tu experiencia en el área', verbose_name='Descripción de la propuesta'),
        ),
    ]
