# Generated by Django 5.1.2 on 2026-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_cotizacion_descripcion_propuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la que el administrador rechazó esta cotización', verbose_name='Motivo del rechazo'),
        ),
    ]
