# Generated by Django 5.1.2 on 2026-05-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Sala')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('solicitud', 'Por Solicitud')], default='solicitud', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participantes', models.ManyToManyField(blank=True, related_name='salas_chat', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sala_chat', to='solicitudes.solicitudacademica', verbose_name='Solicitud asociada')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('archivo', 'Archivo'), ('sistema', 'Sistema')], default='texto', max_length=10)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='chat_archivos/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_chat', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='mensajes_leidos', to=settings.AUTH_USER_MODEL, verbose_name='Leído por')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat_interno.salachat', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
