# Generated by Django 5.1.2 on 2026-08-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0002_alter_mensajechat_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salachat',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('solicitud', 'Por Solicitud'), ('directa', 'Chat Directo')], default='solicitud', max_length=15),
        ),
    ]
