# Generated by Django 5.1.2 on 2026-09-03 05:38

import chat_interno.models
import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0003_add_directa_tipo_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='archivo_nombre',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nombre original del archivo'),
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=settings.PRIVATE_MEDIA_ROOT), upload_to=chat_interno.models.chat_upload_path, verbose_name='Archivo adjunto'),
        ),
    ]
