# Generated by Django 5.1.2 on 2026-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interno', '0004_mensajechat_archivo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='editado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editado en'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
