# Generated by Django 5.1.2 on 2026-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreporte',
            name='solucion',
            field=models.TextField(blank=True, default='', help_text='Solución aplicada al resolver el incidente (solo visible en admin)'),
        ),
    ]
